/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetManager: typeof import('./src/components/panels/AssetManager.vue')['default']
    Attributes: typeof import('./src/components/panels/Attributes.vue')['default']
    BottomAssetPanel: typeof import('./src/components/BottomAssetPanel.vue')['default']
    CameraAttr: typeof import('./src/components/panels/CameraAttr.vue')['default']
    DialogOverlayPanel: typeof import('./src/components/panels/DialogOverlayPanel.vue')['default']
    EasingPicker: typeof import('./src/components/timeline/EasingPicker.vue')['default']
    GeometryAttr: typeof import('./src/components/panels/GeometryAttr.vue')['default']
    HelperAttr: typeof import('./src/components/panels/HelperAttr.vue')['default']
    LeftEditPanel: typeof import('./src/components/LeftEditPanel.vue')['default']
    LightAttr: typeof import('./src/components/panels/LightAttr.vue')['default']
    MaterialAttr: typeof import('./src/components/panels/MaterialAttr.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NFloatButtonGroup: typeof import('naive-ui')['NFloatButtonGroup']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    NumberInput: typeof import('./src/components/panels/NumberInput.vue')['default']
    NUpload: typeof import('naive-ui')['NUpload']
    PluginManager: typeof import('./src/components/panels/PluginManager.vue')['default']
    ProjectAttr: typeof import('./src/components/panels/ProjectAttr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./src/components/Scene.vue')['default']
    SceneAttr: typeof import('./src/components/panels/SceneAttr.vue')['default']
    Timeline: typeof import('./src/components/timeline/Timeline.vue')['default']
    TimelineControls: typeof import('./src/components/timeline/TimelineControls.vue')['default']
    TimelineHeader: typeof import('./src/components/timeline/TimelineHeader.vue')['default']
    TimelineTrack: typeof import('./src/components/timeline/TimelineTrack.vue')['default']
  }
}
