/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetManager: typeof import('./src/components/panles/AssetManager.vue')['default']
    Attributes: typeof import('./src/components/panles/Attributes.vue')['default']
    BottomAssetPanel: typeof import('./src/components/BottomAssetPanel.vue')['default']
    CameraAttr: typeof import('./src/components/panles/CameraAttr.vue')['default']
    GeometryAttr: typeof import('./src/components/panles/GeometryAttr.vue')['default']
    HelperAttr: typeof import('./src/components/panles/HelperAttr.vue')['default']
    LeftEditPanel: typeof import('./src/components/LeftEditPanel.vue')['default']
    LightAttr: typeof import('./src/components/panles/LightAttr.vue')['default']
    MaterialAttr: typeof import('./src/components/panles/MaterialAttr.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NFloatButtonGroup: typeof import('naive-ui')['NFloatButtonGroup']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    NUpload: typeof import('naive-ui')['NUpload']
    ProjectAttr: typeof import('./src/components/panles/ProjectAttr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./src/components/Scene.vue')['default']
    SceneAttr: typeof import('./src/components/panles/SceneAttr.vue')['default']
  }
}
